telegram:
  bot-name: ${BOT_NAME:TelegramBotName}
  bot-token: ${BOT_TOKEN:TelegramBotToken}
spring:
  application:
    name: telegram-bot
server:
  port: 8081

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true