spring:
  application:
    name: cafe-api
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeeBot_DB
    username: postgres
    password: 123
  jpa:
    generate-ddl: false
    show-sql: false
  sql:
    init:
      mode: always
server:
  port: 8080

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}